name = "donabeya"
author = "donabe8898"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f547e1a798c31dc09058ad7611d49ad93bf7cb21dd71f1dc44514045d00cdbb2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
