name = "donabeya"
author = "donabe8898"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95abbdf4867812743baa7efe5b9bab54b7fea26db419a03f4a72bd6fc979fa1c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
