name = "donabeya"
author = "donabe8898"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77e76d0fee1c71da55235661720c6ec8861cc97ea0fb385c377b4ea4b17ccbb0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
