name = "donabeya"
author = "donabe8898"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b51facebed93508c6f46d56e8f7571df751e389cc5669c7b16e20630363528d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
