{
 "title": "どな鯖のだっしゅぼーど！",
 "description": "Displays server stats exported by https://github.com/cpburnz/minecraft-prometheus-exporter",
 "tags": [
  "JVM",
  "minecraft"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "application",
    "query": {
     "query": "label_values(mc_dimension_chunks_loaded, application)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(mc_dimension_chunks_loaded{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "オンラインのプレイヤー",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "人" } },
   "targets": [
    {
     "expr": "mc_player_list{application=\"$application\", instance=\"$instance\", name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "サーバーで遊んだ時間(秒)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\n  sum_over_time(\n    mc_player_list{\n      application=\"$application\",\n      instance=\"$instance\",\n      name!=\"\"\n    }[$__range]\n  )\n) * 10 > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "サーバーの人数",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "人" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "mc_player_list{application=\"$application\", instance=\"$instance\", name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "オンラインのメンバー",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 17 },
   "targets": [
    {
     "expr": "mc_player_list{application=\"$application\", instance=\"$instance\", name!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_info{application=\"$application\", instance=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  { "title": "Minecraft Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "# Chunks Loaded",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "mc_dimension_chunks_loaded{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "95th Percentile Tick Time by World",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mc_dimension_tick_seconds_bucket[$__rate_interval])) by (name, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Tick Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mc_server_tick_seconds_bucket{application=\"$application\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Server Tick Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "clamp_max(1 / histogram_quantile(0.95, sum(rate(mc_server_tick_seconds_bucket{application=\"$application\", instance=\"$instance\"}[$__rate_interval])) by (le)), 20)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tick Rate By World",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "targets": [
    {
     "expr": "clamp_max(1 / histogram_quantile(0.95, sum(rate(mc_dimension_tick_seconds_bucket[$__rate_interval])) by (name, le)), 20)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "読み込んでいるエンティティ",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 68 },
   "targets": [
    { "expr": "mc_entities_total", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "JVM Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 101 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{application=\"$application\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{application=\"$application\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_committed{application=\"$application\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{application=\"$application\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{application=\"$application\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_committed{application=\"$application\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 130 },
   "repeat": "mempool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{application=\"$application\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{application=\"$application\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Mem Pool: PS Eden",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"PS Eden Space\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"PS Eden Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"PS Eden Space\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "JVM Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Mem Pool: Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: Code Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: PS Survivor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"PS Survivor Space\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"PS Survivor Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"PS Survivor Space\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: PS Old",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"PS Old Gen\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"PS Old Gen\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"PS Old Gen\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "JVM Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}